/**
 * Client-side export helpers.
 * All functions run entirely in the browser — no server round-trip.
 */

import type { ParsedMission, RankedVehicle, MatchedVehicle, ExplainResponse } from "./types";

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

function fmtUsd(v: number | null): string {
  if (v === null) return "—";
  if (v >= 1_000_000) return `$${(v / 1_000_000).toFixed(1)}M`;
  return `$${v.toLocaleString()}`;
}

function fmtNull(v: string | number | null | undefined): string {
  return v == null ? "—" : String(v);
}

export interface ExportPayload {
  mission: ParsedMission;
  ranked: RankedVehicle[];
  eliminated: MatchedVehicle[];
  explanation: ExplainResponse | null;
  generatedAt?: string;
}

function buildTextLines(payload: ExportPayload): string[] {
  const { mission, ranked, eliminated, explanation, generatedAt } = payload;
  const ts = generatedAt ?? new Date().toISOString();
  const lines: string[] = [];

  lines.push("=".repeat(60));
  lines.push("AI Launch Vehicle Selector — Mission Report");
  lines.push(`Generated: ${ts}`);
  lines.push("=".repeat(60));
  lines.push("");

  // Mission requirements
  lines.push("MISSION REQUIREMENTS");
  lines.push("-".repeat(40));
  lines.push(`Payload Mass:           ${fmtNull(mission.payload_mass_kg != null ? `${mission.payload_mass_kg} kg` : null)}`);
  lines.push(`Orbit Type:             ${fmtNull(mission.orbit_type)}`);
  lines.push(`Target Altitude:        ${fmtNull(mission.target_altitude_km != null ? `${mission.target_altitude_km} km` : null)}`);
  lines.push(`Budget Ceiling:         ${fmtUsd(mission.budget_usd)}`);
  lines.push(`Max Lead Time:          ${fmtNull(mission.schedule_months != null ? `${mission.schedule_months} months` : null)}`);
  lines.push(`Inclination Flex:       ${fmtNull(mission.inclination_flexibility_required)}`);
  lines.push(`Parse Confidence:       ${mission.parse_confidence.toUpperCase()}`);
  lines.push("");

  // AI explanation
  if (explanation) {
    lines.push("AI RECOMMENDATION");
    lines.push("-".repeat(40));
    lines.push(explanation.explanation);
    lines.push("");
  }

  // Ranked vehicles
  lines.push(`RANKED LAUNCH OPTIONS (${ranked.length} viable)`);
  lines.push("-".repeat(40));
  if (ranked.length === 0) {
    lines.push("No vehicles passed all constraints.");
  } else {
    ranked.forEach((m) => {
      lines.push(`#${m.rank}  ${m.entry.vehicle} (${m.entry.provider})`);
      lines.push(`    Type:          ${m.entry.type}`);
      lines.push(`    Score:         ${m.score}/100`);
      lines.push(`    Est. Cost:     ${fmtUsd(m.estimated_cost_usd)}`);
      lines.push(`    Lead Time:     ${m.entry.integration.lead_time_months.min}–${m.entry.integration.lead_time_months.max} months`);
      lines.push(`    Orbit Flex:    ${m.entry.orbit_options.inclination_flexibility}`);
      lines.push(`    Score Detail:  Cost ${m.score_breakdown.cost_score} | Schedule ${m.score_breakdown.schedule_score} | Orbit ${m.score_breakdown.orbit_score}`);
      lines.push("");
    });
  }

  // Eliminated vehicles
  if (eliminated.length > 0) {
    lines.push(`ELIMINATED OPTIONS (${eliminated.length})`);
    lines.push("-".repeat(40));
    eliminated.forEach((m) => {
      lines.push(`  ${m.entry.vehicle} (${m.entry.provider})`);
      if (m.elimination_reason) lines.push(`    Reason: ${m.elimination_reason}`);
    });
    lines.push("");
  }

  lines.push("=".repeat(60));
  lines.push("Generated by IBM Bob Builders Challenge — AI Launch Vehicle Selector");
  return lines;
}

function buildMarkdown(payload: ExportPayload): string {
  const { mission, ranked, eliminated, explanation, generatedAt } = payload;
  const ts = generatedAt ?? new Date().toISOString();
  const md: string[] = [];

  md.push("# AI Launch Vehicle Selector — Mission Report");
  md.push(`*Generated: ${ts}*`);
  md.push("");

  md.push("## Mission Requirements");
  md.push("");
  md.push("| Field | Value |");
  md.push("|---|---|");
  md.push(`| Payload Mass | ${fmtNull(mission.payload_mass_kg != null ? `${mission.payload_mass_kg} kg` : null)} |`);
  md.push(`| Orbit Type | ${fmtNull(mission.orbit_type)} |`);
  md.push(`| Target Altitude | ${fmtNull(mission.target_altitude_km != null ? `${mission.target_altitude_km} km` : null)} |`);
  md.push(`| Budget Ceiling | ${fmtUsd(mission.budget_usd)} |`);
  md.push(`| Max Lead Time | ${fmtNull(mission.schedule_months != null ? `${mission.schedule_months} months` : null)} |`);
  md.push(`| Inclination Flexibility | ${fmtNull(mission.inclination_flexibility_required)} |`);
  md.push(`| Parse Confidence | **${mission.parse_confidence.toUpperCase()}** |`);
  md.push("");

  if (explanation) {
    md.push("## AI Recommendation");
    md.push("");
    md.push(explanation.explanation);
    md.push("");
  }

  md.push(`## Ranked Launch Options (${ranked.length} viable)`);
  md.push("");
  if (ranked.length === 0) {
    md.push("> No vehicles passed all constraints.");
  } else {
    md.push("| Rank | Vehicle | Provider | Score | Est. Cost | Lead Time | Orbit Flex |");
    md.push("|---|---|---|---|---|---|---|");
    ranked.forEach((m) => {
      md.push(
        `| #${m.rank} | ${m.entry.vehicle} | ${m.entry.provider} | ${m.score} | ${fmtUsd(m.estimated_cost_usd)} | ${m.entry.integration.lead_time_months.min}–${m.entry.integration.lead_time_months.max} mo | ${m.entry.orbit_options.inclination_flexibility} |`
      );
    });
  }
  md.push("");

  if (eliminated.length > 0) {
    md.push(`## Eliminated Options (${eliminated.length})`);
    md.push("");
    eliminated.forEach((m) => {
      md.push(`- **${m.entry.vehicle}** (${m.entry.provider})${m.elimination_reason ? ` — ${m.elimination_reason}` : ""}`);
    });
    md.push("");
  }

  md.push("---");
  md.push("*Generated by IBM Bob Builders Challenge — AI Launch Vehicle Selector*");
  return md.join("\n");
}

function buildCsv(payload: ExportPayload): string {
  const rows: string[][] = [];
  rows.push([
    "Rank", "Vehicle", "Provider", "Type", "Score",
    "Cost Score", "Schedule Score", "Orbit Score",
    "Est. Cost USD", "Lead Time Min (mo)", "Lead Time Max (mo)",
    "Inclination Flexibility", "Orbit Types", "Status", "Notes"
  ]);
  payload.ranked.forEach((m) => {
    rows.push([
      String(m.rank),
      m.entry.vehicle,
      m.entry.provider,
      m.entry.type,
      String(m.score),
      String(m.score_breakdown.cost_score),
      String(m.score_breakdown.schedule_score),
      String(m.score_breakdown.orbit_score),
      m.estimated_cost_usd != null ? String(m.estimated_cost_usd) : "",
      String(m.entry.integration.lead_time_months.min),
      String(m.entry.integration.lead_time_months.max),
      m.entry.orbit_options.inclination_flexibility,
      m.entry.orbit_options.supported_orbit_types.join("; "),
      m.entry.status,
      m.entry.notes,
    ]);
  });
  payload.eliminated.forEach((m) => {
    rows.push([
      "ELIMINATED",
      m.entry.vehicle,
      m.entry.provider,
      m.entry.type,
      "", "", "", "", "",
      String(m.entry.integration.lead_time_months.min),
      String(m.entry.integration.lead_time_months.max),
      m.entry.orbit_options.inclination_flexibility,
      m.entry.orbit_options.supported_orbit_types.join("; "),
      m.entry.status,
      m.elimination_reason ?? m.entry.notes,
    ]);
  });

  return rows
    .map((r) => r.map((cell) => `"${cell.replace(/"/g, '""')}"`).join(","))
    .join("\n");
}

// ---------------------------------------------------------------------------
// Public download functions
// ---------------------------------------------------------------------------

function triggerDownload(filename: string, content: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function triggerDownloadBytes(filename: string, bytes: Blob): void {
  const url = URL.createObjectURL(bytes);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadTxt(payload: ExportPayload): void {
  triggerDownload("mission-report.txt", buildTextLines(payload).join("\n"), "text/plain");
}

export function downloadMarkdown(payload: ExportPayload): void {
  triggerDownload("mission-report.md", buildMarkdown(payload), "text/markdown");
}

export function downloadJson(payload: ExportPayload): void {
  const data = {
    generatedAt: payload.generatedAt ?? new Date().toISOString(),
    mission: payload.mission,
    ranked: payload.ranked,
    eliminated: payload.eliminated,
    explanation: payload.explanation,
  };
  triggerDownload("mission-report.json", JSON.stringify(data, null, 2), "application/json");
}

export function downloadCsv(payload: ExportPayload): void {
  triggerDownload("mission-report.csv", buildCsv(payload), "text/csv");
}

export async function downloadPdf(payload: ExportPayload): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const pageW = doc.internal.pageSize.getWidth();
  const margin = 15;
  const contentW = pageW - margin * 2;
  let y = margin;

  const line = (text: string, size = 10, style: "normal" | "bold" = "normal", color = "#1e293b") => {
    doc.setFontSize(size);
    doc.setFont("helvetica", style);
    doc.setTextColor(color);
    const wrapped = doc.splitTextToSize(text, contentW);
    if (y + wrapped.length * (size * 0.4) > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage();
      y = margin;
    }
    doc.text(wrapped, margin, y);
    y += wrapped.length * (size * 0.4) + 1;
  };
  const gap = (n = 4) => { y += n; };
  const rule = () => {
    doc.setDrawColor("#e2e8f0");
    doc.line(margin, y, pageW - margin, y);
    y += 4;
  };

  const ts = payload.generatedAt ?? new Date().toISOString();
  const { mission, ranked, eliminated, explanation } = payload;

  line("AI Launch Vehicle Selector — Mission Report", 16, "bold", "#0284c7");
  line(`Generated: ${ts}`, 8, "normal", "#64748b");
  gap();
  rule();

  line("MISSION REQUIREMENTS", 11, "bold");
  gap(2);
  const mFields = [
    ["Payload Mass", mission.payload_mass_kg != null ? `${mission.payload_mass_kg} kg` : "—"],
    ["Orbit Type", fmtNull(mission.orbit_type)],
    ["Target Altitude", mission.target_altitude_km != null ? `${mission.target_altitude_km} km` : "—"],
    ["Budget Ceiling", fmtUsd(mission.budget_usd)],
    ["Max Lead Time", mission.schedule_months != null ? `${mission.schedule_months} months` : "—"],
    ["Inclination Flex", fmtNull(mission.inclination_flexibility_required)],
    ["Parse Confidence", mission.parse_confidence.toUpperCase()],
  ];
  mFields.forEach(([label, val]) => {
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor("#475569");
    doc.text(`${label}:`, margin, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor("#1e293b");
    doc.text(val, margin + 42, y);
    y += 5;
  });
  gap();
  rule();

  if (explanation) {
    line("AI RECOMMENDATION", 11, "bold");
    gap(2);
    line(explanation.explanation, 9, "normal", "#334155");
    gap();
    rule();
  }

  line(`RANKED LAUNCH OPTIONS (${ranked.length} viable)`, 11, "bold");
  gap(2);
  if (ranked.length === 0) {
    line("No vehicles passed all constraints.", 9, "normal", "#94a3b8");
  } else {
    ranked.forEach((m) => {
      line(`#${m.rank}  ${m.entry.vehicle}  —  ${m.entry.provider}`, 10, "bold", "#0369a1");
      line(`Score: ${m.score}/100  |  Est. Cost: ${fmtUsd(m.estimated_cost_usd)}  |  Lead Time: ${m.entry.integration.lead_time_months.min}–${m.entry.integration.lead_time_months.max} mo  |  Orbit Flex: ${m.entry.orbit_options.inclination_flexibility}`, 8, "normal", "#334155");
      line(`Score Detail — Cost: ${m.score_breakdown.cost_score}  Schedule: ${m.score_breakdown.schedule_score}  Orbit: ${m.score_breakdown.orbit_score}`, 8, "normal", "#64748b");
      gap(2);
    });
  }

  if (eliminated.length > 0) {
    rule();
    line(`ELIMINATED OPTIONS (${eliminated.length})`, 11, "bold");
    gap(2);
    eliminated.forEach((m) => {
      line(`${m.entry.vehicle} (${m.entry.provider})`, 9, "bold", "#b91c1c");
      if (m.elimination_reason) line(m.elimination_reason, 8, "normal", "#64748b");
      gap(2);
    });
  }

  rule();
  line("Generated by IBM Bob Builders Challenge — AI Launch Vehicle Selector", 8, "normal", "#94a3b8");

  doc.save("mission-report.pdf");
}

export async function downloadDocx(payload: ExportPayload): Promise<void> {
  const {
    Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell,
    WidthType, BorderStyle, AlignmentType,
  } = await import("docx");

  const ts = payload.generatedAt ?? new Date().toISOString();
  const { mission, ranked, eliminated, explanation } = payload;

  const h1 = (text: string) =>
    new Paragraph({ text, heading: HeadingLevel.HEADING_1, spacing: { after: 120 } });
  const h2 = (text: string) =>
    new Paragraph({ text, heading: HeadingLevel.HEADING_2, spacing: { before: 240, after: 120 } });
  const body = (text: string) =>
    new Paragraph({ children: [new TextRun({ text, size: 20 })], spacing: { after: 80 } });
  const kv = (key: string, val: string) =>
    new Paragraph({
      spacing: { after: 60 },
      children: [
        new TextRun({ text: `${key}: `, bold: true, size: 20 }),
        new TextRun({ text: val, size: 20 }),
      ],
    });

  const noBorder = { style: BorderStyle.NONE, size: 0, color: "FFFFFF" };
  const cellBorders = { top: noBorder, bottom: noBorder, left: noBorder, right: noBorder };

  const tableHeaderRow = new TableRow({
    children: ["Rank", "Vehicle", "Provider", "Score", "Est. Cost", "Lead Time", "Orbit Flex"].map(
      (h) =>
        new TableCell({
          children: [new Paragraph({ children: [new TextRun({ text: h, bold: true, size: 18 })] })],
          borders: cellBorders,
        })
    ),
  });

  const rankedRows = ranked.map(
    (m) =>
      new TableRow({
        children: [
          `#${m.rank}`,
          m.entry.vehicle,
          m.entry.provider,
          String(m.score),
          fmtUsd(m.estimated_cost_usd),
          `${m.entry.integration.lead_time_months.min}–${m.entry.integration.lead_time_months.max} mo`,
          m.entry.orbit_options.inclination_flexibility,
        ].map(
          (val) =>
            new TableCell({
              children: [new Paragraph({ children: [new TextRun({ text: val, size: 18 })] })],
              borders: cellBorders,
            })
        ),
      })
  );

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const sections: any[] = [
    h1("AI Launch Vehicle Selector — Mission Report"),
    body(`Generated: ${ts}`),
    h2("Mission Requirements"),
    kv("Payload Mass", mission.payload_mass_kg != null ? `${mission.payload_mass_kg} kg` : "—"),
    kv("Orbit Type", fmtNull(mission.orbit_type)),
    kv("Target Altitude", mission.target_altitude_km != null ? `${mission.target_altitude_km} km` : "—"),
    kv("Budget Ceiling", fmtUsd(mission.budget_usd)),
    kv("Max Lead Time", mission.schedule_months != null ? `${mission.schedule_months} months` : "—"),
    kv("Inclination Flexibility", fmtNull(mission.inclination_flexibility_required)),
    kv("Parse Confidence", mission.parse_confidence.toUpperCase()),
  ];

  if (explanation) {
    sections.push(h2("AI Recommendation"));
    sections.push(body(explanation.explanation));
  }

  sections.push(h2(`Ranked Launch Options (${ranked.length} viable)`));

  if (ranked.length === 0) {
    sections.push(body("No vehicles passed all constraints."));
  } else {
    sections.push(
      new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: [tableHeaderRow, ...rankedRows],
      })
    );
  }

  if (eliminated.length > 0) {
    sections.push(h2(`Eliminated Options (${eliminated.length})`));
    eliminated.forEach((m) => {
      sections.push(
        new Paragraph({
          spacing: { after: 60 },
          children: [
            new TextRun({ text: `${m.entry.vehicle} (${m.entry.provider})`, bold: true, size: 20 }),
            ...(m.elimination_reason
              ? [new TextRun({ text: ` — ${m.elimination_reason}`, size: 20, color: "991B1B" })]
              : []),
          ],
        })
      );
    });
  }

  sections.push(
    new Paragraph({
      spacing: { before: 400 },
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({
          text: "Generated by IBM Bob Builders Challenge — AI Launch Vehicle Selector",
          size: 16,
          color: "94A3B8",
          italics: true,
        }),
      ],
    })
  );

  const doc = new Document({ sections: [{ children: sections }] });
  const blob = await Packer.toBlob(doc);
  triggerDownloadBytes("mission-report.docx", blob);
}
